sc-core/config/routes.rb
Rails.application.routes.draw do
  resources :apikeys
  resources :roles
  resources :permissions
  resources :authcredentials
  resources :authmethods
  resources :invoices
  resources :subscriptions
  resources :payments
  resources :creditcards
  resources :cloudcredentials
  resources :clouds
  resources :products
  resources :users
  resources :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sc-core/app/models/account.rb
class Account < ApplicationRecord
end

sc-core/app/models/apikey.rb
class Apikey < ApplicationRecord
end

sc-core/app/models/authcredential.rb
class Authcredential < ApplicationRecord
end

sc-core/app/models/authmethod.rb
class Authmethod < ApplicationRecord
end

sc-core/app/models/cloud.rb
class Cloud < ApplicationRecord
end

sc-core/app/models/cloudcredential.rb
class Cloudcredential < ApplicationRecord
end

sc-core/app/models/creditcard.rb
class Creditcard < ApplicationRecord
end

sc-core/app/models/invoice.rb
class Invoice < ApplicationRecord
end

sc-core/app/models/payment.rb
class Payment < ApplicationRecord
end

sc-core/app/models/permission.rb
class Permission < ApplicationRecord
end

sc-core/app/models/product.rb
class Product < ApplicationRecord
end

sc-core/app/models/role.rb
class Role < ApplicationRecord
end

sc-core/app/models/subscription.rb
class Subscription < ApplicationRecord
end

sc-core/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

sc-core/app/controllers/authmethods_controller.rb
class AuthmethodsController < ApplicationController
  before_action :set_authmethod, only: [:show, :edit, :update, :destroy]

  # GET /authmethods
  # GET /authmethods.json
  def index
    @authmethods = Authmethod.all
  end

  # GET /authmethods/1
  # GET /authmethods/1.json
  def show
  end

  # GET /authmethods/new
  def new
    @authmethod = Authmethod.new
  end

  # GET /authmethods/1/edit
  def edit
  end

  # POST /authmethods
  # POST /authmethods.json
  def create
    @authmethod = Authmethod.new(authmethod_params)

    respond_to do |format|
      if @authmethod.save
        format.html { redirect_to @authmethod, notice: 'Authmethod was successfully created.' }
        format.json { render :show, status: :created, location: @authmethod }
      else
        format.html { render :new }
        format.json { render json: @authmethod.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authmethods/1
  # PATCH/PUT /authmethods/1.json
  def update
    respond_to do |format|
      if @authmethod.update(authmethod_params)
        format.html { redirect_to @authmethod, notice: 'Authmethod was successfully updated.' }
        format.json { render :show, status: :ok, location: @authmethod }
      else
        format.html { render :edit }
        format.json { render json: @authmethod.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authmethods/1
  # DELETE /authmethods/1.json
  def destroy
    @authmethod.destroy
    respond_to do |format|
      format.html { redirect_to authmethods_url, notice: 'Authmethod was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_authmethod
      @authmethod = Authmethod.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def authmethod_params
      params.require(:authmethod).permit(:uuid, :endpoint, :properties)
    end
end

sc-core/app/helpers/accounts_helper.rb
module AccountsHelper
end

sc-core/app/helpers/apikeys_helper.rb
module ApikeysHelper
end

sc-core/app/helpers/authmethods_helper.rb
module AuthmethodsHelper
end

sc-core/app/helpers/clouds_helper.rb
module CloudsHelper
end

sc-core/app/helpers/invoices_helper.rb
module InvoicesHelper
end

sc-core/app/helpers/payments_helper.rb
module PaymentsHelper
end

sc-core/app/helpers/roles_helper.rb
module RolesHelper
end

sc-core/app/helpers/users_helper.rb
module UsersHelper
end

sc-core/app/views/authmethods/_form.html.erb
<%= form_with(model: authmethod, local: true) do |form| %>
  <% if authmethod.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(authmethod.errors.count, "error") %> prohibited this authmethod from being saved:</h2>

      <ul>
      <% authmethod.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :uuid %>
    <%= form.text_field :uuid, id: :authmethod_uuid %>
  </div>

  <div class="field">
    <%= form.label :endpoint %>
    <%= form.text_field :endpoint, id: :authmethod_endpoint %>
  </div>

  <div class="field">
    <%= form.label :properties %>
    <%= form.text_area :properties, id: :authmethod_properties %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

sc-core/app/views/authmethods/edit.html.erb
<h1>Editing Authmethod</h1>

<%= render 'form', authmethod: @authmethod %>

<%= link_to 'Show', @authmethod %> |
<%= link_to 'Back', authmethods_path %>

sc-core/app/views/authmethods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authmethods</h1>

<table>
  <thead>
    <tr>
      <th>Uuid</th>
      <th>Endpoint</th>
      <th>Properties</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authmethods.each do |authmethod| %>
      <tr>
        <td><%= authmethod.uuid %></td>
        <td><%= authmethod.endpoint %></td>
        <td><%= authmethod.properties %></td>
        <td><%= link_to 'Show', authmethod %></td>
        <td><%= link_to 'Edit', edit_authmethod_path(authmethod) %></td>
        <td><%= link_to 'Destroy', authmethod, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Authmethod', new_authmethod_path %>

sc-core/app/views/authmethods/new.html.erb
<h1>New Authmethod</h1>

<%= render 'form', authmethod: @authmethod %>

<%= link_to 'Back', authmethods_path %>

sc-core/app/views/authmethods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uuid:</strong>
  <%= @authmethod.uuid %>
</p>

<p>
  <strong>Endpoint:</strong>
  <%= @authmethod.endpoint %>
</p>

<p>
  <strong>Properties:</strong>
  <%= @authmethod.properties %>
</p>

<%= link_to 'Edit', edit_authmethod_path(@authmethod) %> |
<%= link_to 'Back', authmethods_path %>