sc-core/config/routes.rb
Rails.application.routes.draw do
  resources :apikeys
  resources :roles
  resources :permissions
  resources :authcredentials
  resources :authmethods
  resources :invoices
  resources :subscriptions
  resources :payments
  resources :creditcards
  resources :cloudcredentials
  resources :clouds
  resources :products
  resources :users
  resources :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sc-core/app/models/account.rb
class Account < ApplicationRecord
end

sc-core/app/models/apikey.rb
class Apikey < ApplicationRecord
end

sc-core/app/models/authcredential.rb
class Authcredential < ApplicationRecord
end

sc-core/app/models/authmethod.rb
class Authmethod < ApplicationRecord
end

sc-core/app/models/cloud.rb
class Cloud < ApplicationRecord
end

sc-core/app/models/cloudcredential.rb
class Cloudcredential < ApplicationRecord
end

sc-core/app/models/creditcard.rb
class Creditcard < ApplicationRecord
end

sc-core/app/models/invoice.rb
class Invoice < ApplicationRecord
end

sc-core/app/models/payment.rb
class Payment < ApplicationRecord
end

sc-core/app/models/permission.rb
class Permission < ApplicationRecord
end

sc-core/app/models/product.rb
class Product < ApplicationRecord
end

sc-core/app/models/role.rb
class Role < ApplicationRecord
end

sc-core/app/models/subscription.rb
class Subscription < ApplicationRecord
end

sc-core/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

sc-core/app/controllers/cloudcredentials_controller.rb
class CloudcredentialsController < ApplicationController
  before_action :set_cloudcredential, only: [:show, :edit, :update, :destroy]

  # GET /cloudcredentials
  # GET /cloudcredentials.json
  def index
    @cloudcredentials = Cloudcredential.all
  end

  # GET /cloudcredentials/1
  # GET /cloudcredentials/1.json
  def show
  end

  # GET /cloudcredentials/new
  def new
    @cloudcredential = Cloudcredential.new
  end

  # GET /cloudcredentials/1/edit
  def edit
  end

  # POST /cloudcredentials
  # POST /cloudcredentials.json
  def create
    @cloudcredential = Cloudcredential.new(cloudcredential_params)

    respond_to do |format|
      if @cloudcredential.save
        format.html { redirect_to @cloudcredential, notice: 'Cloudcredential was successfully created.' }
        format.json { render :show, status: :created, location: @cloudcredential }
      else
        format.html { render :new }
        format.json { render json: @cloudcredential.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cloudcredentials/1
  # PATCH/PUT /cloudcredentials/1.json
  def update
    respond_to do |format|
      if @cloudcredential.update(cloudcredential_params)
        format.html { redirect_to @cloudcredential, notice: 'Cloudcredential was successfully updated.' }
        format.json { render :show, status: :ok, location: @cloudcredential }
      else
        format.html { render :edit }
        format.json { render json: @cloudcredential.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cloudcredentials/1
  # DELETE /cloudcredentials/1.json
  def destroy
    @cloudcredential.destroy
    respond_to do |format|
      format.html { redirect_to cloudcredentials_url, notice: 'Cloudcredential was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cloudcredential
      @cloudcredential = Cloudcredential.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cloudcredential_params
      params.require(:cloudcredential).permit(:uuid, :properties)
    end
end

sc-core/app/helpers/accounts_helper.rb
module AccountsHelper
end

sc-core/app/helpers/apikeys_helper.rb
module ApikeysHelper
end

sc-core/app/helpers/cloudcredentials_helper.rb
module CloudcredentialsHelper
end

sc-core/app/helpers/clouds_helper.rb
module CloudsHelper
end

sc-core/app/helpers/invoices_helper.rb
module InvoicesHelper
end

sc-core/app/helpers/payments_helper.rb
module PaymentsHelper
end

sc-core/app/helpers/roles_helper.rb
module RolesHelper
end

sc-core/app/helpers/users_helper.rb
module UsersHelper
end

sc-core/app/views/cloudcredentials/_form.html.erb
<%= form_with(model: cloudcredential, local: true) do |form| %>
  <% if cloudcredential.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cloudcredential.errors.count, "error") %> prohibited this cloudcredential from being saved:</h2>

      <ul>
      <% cloudcredential.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :uuid %>
    <%= form.text_field :uuid, id: :cloudcredential_uuid %>
  </div>

  <div class="field">
    <%= form.label :properties %>
    <%= form.text_area :properties, id: :cloudcredential_properties %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

sc-core/app/views/cloudcredentials/edit.html.erb
<h1>Editing Cloudcredential</h1>

<%= render 'form', cloudcredential: @cloudcredential %>

<%= link_to 'Show', @cloudcredential %> |
<%= link_to 'Back', cloudcredentials_path %>

sc-core/app/views/cloudcredentials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cloudcredentials</h1>

<table>
  <thead>
    <tr>
      <th>Uuid</th>
      <th>Properties</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cloudcredentials.each do |cloudcredential| %>
      <tr>
        <td><%= cloudcredential.uuid %></td>
        <td><%= cloudcredential.properties %></td>
        <td><%= link_to 'Show', cloudcredential %></td>
        <td><%= link_to 'Edit', edit_cloudcredential_path(cloudcredential) %></td>
        <td><%= link_to 'Destroy', cloudcredential, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cloudcredential', new_cloudcredential_path %>

sc-core/app/views/cloudcredentials/new.html.erb
<h1>New Cloudcredential</h1>

<%= render 'form', cloudcredential: @cloudcredential %>

<%= link_to 'Back', cloudcredentials_path %>

sc-core/app/views/cloudcredentials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uuid:</strong>
  <%= @cloudcredential.uuid %>
</p>

<p>
  <strong>Properties:</strong>
  <%= @cloudcredential.properties %>
</p>

<%= link_to 'Edit', edit_cloudcredential_path(@cloudcredential) %> |
<%= link_to 'Back', cloudcredentials_path %>