sc-core/config/routes.rb
Rails.application.routes.draw do
  resources :apikeys
  resources :roles
  resources :permissions
  resources :authcredentials
  resources :authmethods
  resources :invoices
  resources :subscriptions
  resources :payments
  resources :creditcards
  resources :cloudcredentials
  resources :clouds
  resources :products
  resources :users
  resources :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sc-core/app/models/account.rb
class Account < ApplicationRecord
end

sc-core/app/models/apikey.rb
class Apikey < ApplicationRecord
end

sc-core/app/models/authcredential.rb
class Authcredential < ApplicationRecord
end

sc-core/app/models/authmethod.rb
class Authmethod < ApplicationRecord
end

sc-core/app/models/cloud.rb
class Cloud < ApplicationRecord
end

sc-core/app/models/cloudcredential.rb
class Cloudcredential < ApplicationRecord
end

sc-core/app/models/creditcard.rb
class Creditcard < ApplicationRecord
end

sc-core/app/models/invoice.rb
class Invoice < ApplicationRecord
end

sc-core/app/models/payment.rb
class Payment < ApplicationRecord
end

sc-core/app/models/permission.rb
class Permission < ApplicationRecord
end

sc-core/app/models/product.rb
class Product < ApplicationRecord
end

sc-core/app/models/role.rb
class Role < ApplicationRecord
end

sc-core/app/models/subscription.rb
class Subscription < ApplicationRecord
end

sc-core/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

sc-core/app/controllers/clouds_controller.rb
class CloudsController < ApplicationController
  before_action :set_cloud, only: [:show, :edit, :update, :destroy]

  # GET /clouds
  # GET /clouds.json
  def index
    @clouds = Cloud.all
  end

  # GET /clouds/1
  # GET /clouds/1.json
  def show
  end

  # GET /clouds/new
  def new
    @cloud = Cloud.new
  end

  # GET /clouds/1/edit
  def edit
  end

  # POST /clouds
  # POST /clouds.json
  def create
    @cloud = Cloud.new(cloud_params)

    respond_to do |format|
      if @cloud.save
        format.html { redirect_to @cloud, notice: 'Cloud was successfully created.' }
        format.json { render :show, status: :created, location: @cloud }
      else
        format.html { render :new }
        format.json { render json: @cloud.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clouds/1
  # PATCH/PUT /clouds/1.json
  def update
    respond_to do |format|
      if @cloud.update(cloud_params)
        format.html { redirect_to @cloud, notice: 'Cloud was successfully updated.' }
        format.json { render :show, status: :ok, location: @cloud }
      else
        format.html { render :edit }
        format.json { render json: @cloud.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clouds/1
  # DELETE /clouds/1.json
  def destroy
    @cloud.destroy
    respond_to do |format|
      format.html { redirect_to clouds_url, notice: 'Cloud was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cloud
      @cloud = Cloud.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cloud_params
      params.require(:cloud).permit(:endpoint, :properties, :uuid)
    end
end

sc-core/app/helpers/accounts_helper.rb
module AccountsHelper
end

sc-core/app/helpers/apikeys_helper.rb
module ApikeysHelper
end

sc-core/app/helpers/clouds_helper.rb
module CloudsHelper
end

sc-core/app/helpers/invoices_helper.rb
module InvoicesHelper
end

sc-core/app/helpers/payments_helper.rb
module PaymentsHelper
end

sc-core/app/helpers/products_helper.rb
module ProductsHelper
end

sc-core/app/helpers/roles_helper.rb
module RolesHelper
end

sc-core/app/helpers/users_helper.rb
module UsersHelper
end

sc-core/app/views/clouds/_form.html.erb
<%= form_with(model: cloud, local: true) do |form| %>
  <% if cloud.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cloud.errors.count, "error") %> prohibited this cloud from being saved:</h2>

      <ul>
      <% cloud.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :endpoint %>
    <%= form.text_field :endpoint, id: :cloud_endpoint %>
  </div>

  <div class="field">
    <%= form.label :properties %>
    <%= form.text_area :properties, id: :cloud_properties %>
  </div>

  <div class="field">
    <%= form.label :uuid %>
    <%= form.text_field :uuid, id: :cloud_uuid %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

sc-core/app/views/clouds/edit.html.erb
<h1>Editing Cloud</h1>

<%= render 'form', cloud: @cloud %>

<%= link_to 'Show', @cloud %> |
<%= link_to 'Back', clouds_path %>

sc-core/app/views/clouds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clouds</h1>

<table>
  <thead>
    <tr>
      <th>Endpoint</th>
      <th>Properties</th>
      <th>Uuid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clouds.each do |cloud| %>
      <tr>
        <td><%= cloud.endpoint %></td>
        <td><%= cloud.properties %></td>
        <td><%= cloud.uuid %></td>
        <td><%= link_to 'Show', cloud %></td>
        <td><%= link_to 'Edit', edit_cloud_path(cloud) %></td>
        <td><%= link_to 'Destroy', cloud, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cloud', new_cloud_path %>

sc-core/app/views/clouds/new.html.erb
<h1>New Cloud</h1>

<%= render 'form', cloud: @cloud %>

<%= link_to 'Back', clouds_path %>

sc-core/app/views/clouds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Endpoint:</strong>
  <%= @cloud.endpoint %>
</p>

<p>
  <strong>Properties:</strong>
  <%= @cloud.properties %>
</p>

<p>
  <strong>Uuid:</strong>
  <%= @cloud.uuid %>
</p>

<%= link_to 'Edit', edit_cloud_path(@cloud) %> |
<%= link_to 'Back', clouds_path %>