sc-core/config/routes.rb
Rails.application.routes.draw do
  resources :apikeys
  resources :roles
  resources :permissions
  resources :authcredentials
  resources :authmethods
  resources :invoices
  resources :subscriptions
  resources :payments
  resources :creditcards
  resources :cloudcredentials
  resources :clouds
  resources :products
  resources :users
  resources :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sc-core/app/models/account.rb
class Account < ApplicationRecord
end

sc-core/app/models/apikey.rb
class Apikey < ApplicationRecord
end

sc-core/app/models/authcredential.rb
class Authcredential < ApplicationRecord
end

sc-core/app/models/authmethod.rb
class Authmethod < ApplicationRecord
end

sc-core/app/models/cloud.rb
class Cloud < ApplicationRecord
end

sc-core/app/models/cloudcredential.rb
class Cloudcredential < ApplicationRecord
end

sc-core/app/models/creditcard.rb
class Creditcard < ApplicationRecord
end

sc-core/app/models/invoice.rb
class Invoice < ApplicationRecord
end

sc-core/app/models/payment.rb
class Payment < ApplicationRecord
end

sc-core/app/models/permission.rb
class Permission < ApplicationRecord
end

sc-core/app/models/product.rb
class Product < ApplicationRecord
end

sc-core/app/models/role.rb
class Role < ApplicationRecord
end

sc-core/app/models/subscription.rb
class Subscription < ApplicationRecord
end

sc-core/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

sc-core/app/controllers/creditcards_controller.rb
class CreditcardsController < ApplicationController
  before_action :set_creditcard, only: [:show, :edit, :update, :destroy]

  # GET /creditcards
  # GET /creditcards.json
  def index
    @creditcards = Creditcard.all
  end

  # GET /creditcards/1
  # GET /creditcards/1.json
  def show
  end

  # GET /creditcards/new
  def new
    @creditcard = Creditcard.new
  end

  # GET /creditcards/1/edit
  def edit
  end

  # POST /creditcards
  # POST /creditcards.json
  def create
    @creditcard = Creditcard.new(creditcard_params)

    respond_to do |format|
      if @creditcard.save
        format.html { redirect_to @creditcard, notice: 'Creditcard was successfully created.' }
        format.json { render :show, status: :created, location: @creditcard }
      else
        format.html { render :new }
        format.json { render json: @creditcard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /creditcards/1
  # PATCH/PUT /creditcards/1.json
  def update
    respond_to do |format|
      if @creditcard.update(creditcard_params)
        format.html { redirect_to @creditcard, notice: 'Creditcard was successfully updated.' }
        format.json { render :show, status: :ok, location: @creditcard }
      else
        format.html { render :edit }
        format.json { render json: @creditcard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /creditcards/1
  # DELETE /creditcards/1.json
  def destroy
    @creditcard.destroy
    respond_to do |format|
      format.html { redirect_to creditcards_url, notice: 'Creditcard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_creditcard
      @creditcard = Creditcard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def creditcard_params
      params.require(:creditcard).permit(:uuid, :ccnumber, :cvn, :address, :name, :exp)
    end
end

sc-core/app/helpers/accounts_helper.rb
module AccountsHelper
end

sc-core/app/helpers/apikeys_helper.rb
module ApikeysHelper
end

sc-core/app/helpers/clouds_helper.rb
module CloudsHelper
end

sc-core/app/helpers/creditcards_helper.rb
module CreditcardsHelper
end

sc-core/app/helpers/invoices_helper.rb
module InvoicesHelper
end

sc-core/app/helpers/payments_helper.rb
module PaymentsHelper
end

sc-core/app/helpers/roles_helper.rb
module RolesHelper
end

sc-core/app/helpers/users_helper.rb
module UsersHelper
end

sc-core/app/views/creditcards/_form.html.erb
<%= form_with(model: creditcard, local: true) do |form| %>
  <% if creditcard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(creditcard.errors.count, "error") %> prohibited this creditcard from being saved:</h2>

      <ul>
      <% creditcard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :uuid %>
    <%= form.text_field :uuid, id: :creditcard_uuid %>
  </div>

  <div class="field">
    <%= form.label :ccnumber %>
    <%= form.text_field :ccnumber, id: :creditcard_ccnumber %>
  </div>

  <div class="field">
    <%= form.label :cvn %>
    <%= form.number_field :cvn, id: :creditcard_cvn %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :creditcard_address %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :creditcard_name %>
  </div>

  <div class="field">
    <%= form.label :exp %>
    <%= form.text_field :exp, id: :creditcard_exp %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

sc-core/app/views/creditcards/edit.html.erb
<h1>Editing Creditcard</h1>

<%= render 'form', creditcard: @creditcard %>

<%= link_to 'Show', @creditcard %> |
<%= link_to 'Back', creditcards_path %>

sc-core/app/views/creditcards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Creditcards</h1>

<table>
  <thead>
    <tr>
      <th>Uuid</th>
      <th>Ccnumber</th>
      <th>Cvn</th>
      <th>Address</th>
      <th>Name</th>
      <th>Exp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @creditcards.each do |creditcard| %>
      <tr>
        <td><%= creditcard.uuid %></td>
        <td><%= creditcard.ccnumber %></td>
        <td><%= creditcard.cvn %></td>
        <td><%= creditcard.address %></td>
        <td><%= creditcard.name %></td>
        <td><%= creditcard.exp %></td>
        <td><%= link_to 'Show', creditcard %></td>
        <td><%= link_to 'Edit', edit_creditcard_path(creditcard) %></td>
        <td><%= link_to 'Destroy', creditcard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Creditcard', new_creditcard_path %>

sc-core/app/views/creditcards/new.html.erb
<h1>New Creditcard</h1>

<%= render 'form', creditcard: @creditcard %>

<%= link_to 'Back', creditcards_path %>

sc-core/app/views/creditcards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uuid:</strong>
  <%= @creditcard.uuid %>
</p>

<p>
  <strong>Ccnumber:</strong>
  <%= @creditcard.ccnumber %>
</p>

<p>
  <strong>Cvn:</strong>
  <%= @creditcard.cvn %>
</p>

<p>
  <strong>Address:</strong>
  <%= @creditcard.address %>
</p>

<p>
  <strong>Name:</strong>
  <%= @creditcard.name %>
</p>

<p>
  <strong>Exp:</strong>
  <%= @creditcard.exp %>
</p>

<%= link_to 'Edit', edit_creditcard_path(@creditcard) %> |
<%= link_to 'Back', creditcards_path %>